#!/usr/bin/env python3
# encoding=UTF-8

# Copyright © 2022 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import argparse
import re
import sys
import traceback

import gi

gi.require_version('GLib', '2.0')
from gi.repository import GLib

gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

gi.require_version('Gdk', '3.0')
from gi.repository import Gdk

gi.require_version('Vte', '2.91')
from gi.repository import Vte

prog = argparse.ArgumentParser().prog

class Window(Gtk.Window):

    def __init__(self):
        super().__init__(title=prog)
        self.term = Terminal()
        self.add(self.term)
        self.term.drag_dest_add_text_targets()
        self.connect('destroy', Gtk.main_quit)

def get_dl_dir():
    return GLib.get_user_special_dir(GLib.UserDirectory.DIRECTORY_DOWNLOAD)

class Terminal(Vte.Terminal):

    def __init__(self):
        super().__init__()
        self.drag_dest_set(Gtk.DestDefaults.ALL, [], Gdk.DragAction.COPY)
        self.connect('drag-data-received', self.on_drag_data_received)

    def on_drag_data_received(self, widget, drag_context, x, y, data, info, time):
        text = data.get_text()
        if not re.match('^https?://', text):
            return
        cmd = ['yt-dlp', '--', text]
        self.disconnect_by_func(self.on_drag_data_received)
        self.spawn_async(
            Vte.PtyFlags.DEFAULT,
            get_dl_dir(),
            cmd,
            None,
            GLib.SpawnFlags.DEFAULT,
            None, None, -1, None
        )

def excepthook(exctype, value, tb):
    sys.excepthook = None
    def callback():
        tb_text = str.join('', traceback.format_exception(exctype, value, tb))
        dlg = Gtk.MessageDialog(
            modal=True,
            destroy_with_parent=True,
            message_type=Gtk.MessageType.ERROR,
            buttons=Gtk.ButtonsType.CLOSE,
            title=f'{prog} — fatal error',
            text=tb_text,
        )
        dlg.run()
        Gtk.main_quit()
    GLib.idle_add(callback)

def main():
    sys.excepthook = excepthook
    window = Window()
    window.show_all()
    Gtk.main()

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
